### ISSUE TITLE
Wrong register used ?

### ISSUE THREAD

**Issue by LukasBrass** [darnuria/esgi-riscv#3]
https://github.com/darnuria/esgi-riscv/blob/5a32509fcfda76075292c30e5e6c899339dd86c8/exercices/02_conditions.asm#L33
https://github.com/darnuria/esgi-riscv/blob/5a32509fcfda76075292c30e5e6c899339dd86c8/exercices/02_conditions.asm#L38
Using this register may leads to misunderstanding

**Comment by darnuria** [comment]
Thanks a lot fixed in tree https://github.com/darnuria/esgi-riscv/blob/master/exercices/02_conditions.asm#L41 and https://github.com/darnuria/esgi-riscv/blob/master/exercices/02_conditions.asm#L46

commit: f73a95604ff2bc81942790c29a9c2f248b64091e
